#' @export
#'
#' @title Reformatting to original input format.
#' @param peaks Peak data table (matrix) to reformat
#' @param info Information table generated by bct.infogen.
#' @param backup Backup object generated by bct.format.
#' @param p.id Column index of first sample data column in original input table.
#' @param start.ord Character vector containing the sample names in the order of the
#'   original input table
#' @param gn Character vector containing the sample group names.
#' @param csv Logical; should a .csv file be saved?
#' @param n Filename prefix to add to the filename. Required if csv = T.
#' @param wrap Logical; should formatting to original input format be performed? If
#'   wrap == F, function call only saves a .csv file with csv = T.
#' @description Reformats pipeline formatted objects to original input objects and saves
#'   .csv files.
#' @return Produces a character matrix containing the reformatted data table if wrap = T
#'   and saves a .csv file with the specified prefix. If wrap = F only saves a .csv file.

bct.bridge <- function(peaks, info, backup, p.id, start.ord, gn = NULL, csv = F, n = NULL, wrap = T){

  if(wrap){

    peaks <- peaks[, order(colnames(peaks))]
    peaks.la <- backup
    peaks.la[3:nrow(peaks.la), p.id:ncol(peaks.la)] <- t(peaks)

    tmp <- NULL
    for(i in 1:length(start.ord)){
      tmp <- cbind(tmp, peaks.la[, which(peaks.la[2, ] == start.ord[i])])
    }

    peaks.la <- tmp

    colnames(peaks.la) <- peaks.la[2,]
    colnames(peaks.la)[p.id] <- 'Raw.abundance'

    if(csv){
      bct.msg(c(cat('Writing File:\n'),
                paste(n, basename(fname), sep = '_')),
              side = 'none')
      ftab <- bct.tabwrap(peaks.la, c('factor', 'data.table'))
      dir.create(gsub('.csv', '', paste(n, basename(fname), sep = '_')))
      setwd(gsub('.csv', '', paste(n, basename(fname), sep = '_')))
      fwrite(ftab, paste(n, basename(fname), sep = '_'), sep = ';', append = T)
      Sys.sleep(0.5)
      setwd('..')
    }

    return(peaks.la)

    # If given in LaunchAnalyzer format, no need to do table-tricks
  } else {

    if(csv){
      bct.msg(c(cat('Writing File:\n'),
                paste(n, basename(fname), sep = '_')),side = 'none')
      ftab <- bct.tabwrap(peaks, c('factor', 'data.table'))
      dir.create(gsub('.csv', '', paste(n, basename(fname), sep = '_')))
      setwd(gsub('.csv', '', paste(n, basename(fname), sep = '_')))
      fwrite(ftab, paste(n, basename(fname), sep = '_'), sep = ';', append = T)
      Sys.sleep(0.5)
      setwd('..')
    }

  }


    return(peaks)
}
