#' @export
#'
#' @title Compute featurewise p-values of LC-MS data by analysis of variance (ANOVA).
#' @param peaks Input peak data table (matrix)
#' @param info Information table generated by bct.infogen.
#' @param PLOT Logical; should p-value histograms be produced?
#' @param PDF Logical; should a pdf with p-value histograms be produced. Obsolete
#'   command within pipeline, set to F.
#' @param csv Logical; should a .csv file containing the featurewise p-values be produced?
#' @param t Plot title
#' @param adj Logical; should the computed p-values be adjusted (Bonferroni-Holm)?
#' @param plotn Plotting option to compute p-values by information present in information
#'   table. Can be "Group" to compute p-values between sample groups, "Batch" for
#'   p-values between batches, "SeqNr" for p-values between injection sequence indices,
#'   or "All" to compute all of the mentioned p-values.
#' @description Performs ANOVA on the peak data using the information table to compute
#'   p-values per feature. Used to univariately assess the presence of batch effects, as
#'   well as to control if differences between groups (actual variation of interest) is
#'   perserved (courtesy of Prof. C. T. Nakas, Laboratory of Biometry, University of
#'   Thessaly, Volos, Greece).
#' @return Generates a table object containing p-values of all features.

bct.pval <- function(peaks, info, PLOT = TRUE, PDF = FALSE, csv = FALSE, t = "", adj = F,
                     plotn = c("Group", "Batch", "SeqNr", "All"), dens = T) {

  cat("Preparing data...\n\n")

  n.p <- ncol(peaks)

  # intialize objects for peaks
  sitep <- rep(0, n.p)
  timep <- rep(0, n.p)
  groupp <- rep(0, n.p)

  if (class(info$SeqNr) != "integer") {
    info$SeqNr <- as.integer(info$SeqNr)
  }
  # get p-values
  for (i in 1:n.p) {
    crudelm <- aov(peaks[, i] ~ factor(info$SCode) + info$Batch + info$SeqNr)
    viasumunl <- unlist(summary(crudelm))
    groupp[i - 3] <- viasumunl[["Pr(>F)1"]]
    sitep[i - 3] <- viasumunl[["Pr(>F)2"]]
    timep[i - 3] <- viasumunl[["Pr(>F)3"]]
  }

  p.abundances <- matrix()
  p.abundances <- cbind(patientp, sitep, timep)

  if(adj){
    allpadjcb <- as.data.frame(apply(p.abundances, 2, p.adjust, method = "fdr", n = nrow(p.abundances)))
    p.ALL <- cbind(p.abundances, sep = rep(0, nrow(p.abundances)), allpadjcb)
  } else {
    p.ALL <- cbind(p.abundances)
  }

  if (PLOT) {
    if (PDF) {
      pdfname <- readline("Please enter a name for the plotfile, ending in .pdf:\n\n")

      pdf(pdfname)
      hist(patientp, main = paste(t, "Group"), xlab = "P-Value", cex = 3, xlim = c(0,1), probability = T)
      abline(v = median(patientp), lty = 3, col = "red")
      if(dens){
        lines(density(patientp), col = 'blue', lty = 1, lwd = 2)
      }


      hist(sitep, main = paste(t, "Batch"), xlab = "P-Value", cex = 3, xlim = c(0,1), probability = T)
      abline(v = median(sitep), lty = 3, col = "red")
      if(dens){
        lines(density(sitep), col = 'blue', lty = 1, lwd = 2)
      }


      hist(timep, main = paste(t, "Order"), xlab = "P-Value", cex = 3, xlim = c(0,1), probability = T)
      abline(v = median(timep), lty = 3, col = "red")
      if(dens){
        lines(density(timep), col = 'blue', lty = 1, lwd = 2)
      }




      if(adj){
        hist(allpadjcb$patientp, main = paste(t, "Group adj"), xlab = "P-Value", cex = 3, xlim = c(0,1), probability = T)
        abline(v = median(allpadjcb$patientp), lty = 3, col = "red")
        if(dens){
          lines(density(allpadjcb$patientp), col = 'blue', lty = 1, lwd = 2)
        }


        hist(allpadjcb$sitep, main = paste(t, "Batch adj"), xlab = "P-Value", cex = 3, xlim = c(0,1), probability = T)
        abline(v = median(allpadjcb$sitep), lty = 3, col = "red")
        if(dens){
          lines(density(allpadjcb$sitep), col = 'blue', lty = 1, lwd = 2)
        }


        hist(allpadjcb$timep, main = paste(t, "Order adj"), xlab = "P-Value", cex = 3, xlim = c(0,1), probability = T)
        abline(v = median(allpadjcb$timep), lty = 3, col = "red")
        if(dens){
          lines(density(allpadjcb$timep), col = 'blue', lty = 1, lwd = 2)
        }
      }

      suppressMessages(dev.off())

    } else {
      # par(mar = c(4, 5.5, 5, 3), cex.lab = 1.6, cex.axis = 1.3, cex.main = 2)

      if(plotn == 'Group' | plotn == 'All'){
        hist(patientp, main = paste(t, "Group"), xlab = "P-Value", cex = 3, breaks = 15, xlim = c(0,1), probability = T)
        abline(v = median(patientp), lty = 2, col = "red")
        if(dens){
          d <- density(patientp)
          lines(d, col = 'blue', lty = 1, lwd = 2)
        }
      }

      if(plotn == 'Batch' | plotn == 'All'){
        hist(sitep, main = paste(t, "Batch"), xlab = "P-Value", cex = 3, breaks = 15, xlim = c(0,1), probability = T)
        abline(v = median(sitep), lty = 2, col = "red")
        if(dens){
          lines(density(sitep), col = 'blue', lty = 1, lwd = 2)
        }
      }

      if(plotn == 'SeqNr' | plotn == 'All'){
        hist(timep, main = paste(t, "Order"), xlab = "P-Value", cex = 3, breaks = 15, xlim = c(0,1), probability = T)
        abline(v = median(timep), lty = 2, col = "red")
        if(dens){
          lines(density(timep), col = 'blue', lty = 1, lwd = 2)
        }
      }

      if(adj){
        # par(mfrow=c(1,3))
        if(plotn == 'Group' | plotn == 'All'){
          hist(allpadjcb$patientp, main = paste(t, "Group adj"), xlab = "P-Value", cex = 3, breaks = 15, xlim = c(0,1), probability = T)
          abline(v = median(allpadjcb$patientp), lty = 2, col = "red")
          if(dens){
            lines(density(allpadjcb$patientp), col = 'blue', lty = 1, lwd = 2)
          }
        }
        if(plotn == 'Batch' | plotn == 'All'){
          hist(allpadjcb$sitep, main = paste(t, "Batch adj"), xlab = "P-Value", cex = 3, breaks = 15, xlim = c(0,1), probability = T)
          abline(v = median(allpadjcb$sitep), lty = 2, col = "red")
          if(dens){
            lines(density(allpadjcb$sitep), col = 'blue', lty = 1, lwd = 2)
          }
        }
        if(plotn == 'SeqNr' | plotn == 'All'){
          hist(allpadjcb$timep, main = paste(t, "Order adj"), xlab = "P-Value", cex = 3, breaks = 15, xlim = c(0,1), probability = T)
          abline(v = median(allpadjcb$timep), lty = 2, col = "red")
          if(dens){
            lines(density(allpadjcb$timep), col = 'blue', lty = 1, lwd = 2)
          }
        }
      }
    }
  }

  if (csv) {
    csvname <- readline("Please enter a name for the table file, ending in .csv:\n\n")
    write.csv(p.ALL, csvname)
  }
  cat("\nComputations complete!\n")
  return(p.ALL)
}

