#' @export
#'
#' @title Injection sequence modification
#' @param info Information table generated by bct.infogen
#' @param bn Batch name vector, containing batch names as in information table
#' @description Modifies the present injection sequence and produces a continuing sequence.
#'   Uses batch labels to decide the new injection sequence.
#' @return Returns a numeric vector containing the modified injection sequence.

bct.seqmod <- function(info, bn) {

    nb <- length(bn)
    seq <- as.numeric(as.character(info$SeqNr))

    for (i in 2:nb) {

        b.id <- which(info$Batch == bn[i])
        seq.b <- seq[b.id]
        incr <- 100 * i
        seq[b.id] <- incr + as.numeric(info$SeqNr[b.id])
    }

    info$SeqNr <- seq

    return(info)
}

