#' @export
#'
#' @title Feature plotting function
#' @param data.in Input list containing two elements: the peak data table in pipeline
#'   format and the corresponding information table generated by infogen.
#' @param select Feature indices to plot. Can be a vector with multiple indices.
#' @param QC Logical; plot regression lines at hand of quality contol samples (QC = T)
#'   or at hand of study samples?
#' @param seq Logical; plot along injection sequence indices (seq = T) or along batch
#'   labels?
#' @param I.g Information table index of grouping column
#' @param I.b Information table index of batch label column
#' @param I.s Information table index of injection sequence column
#' @param log.t Logical; is the input peak data log-transformed?
#' @param lgd Logical; should a legend be included in the plot?
#' @param r.method Regression method to plot trendline. Can be "lm" for linear model or
#'   "loess" for locally weighted scatterplot smoothing.
#' @param span Span parameter if r.method = "loess". Decides the degree of smoothing.
#' @description Plotting function that takes bct formatted LC-MS data and plots selected
#'   feature intensities against either injection sequence or batch labels. Uses the
#'   ggplot package for plotting.
#' @return Produces a ggplot object.


bct.linearity <- function(data.in, select, QC = T, seq = T, I.g = 1, I.b = 2, I.s = 3, log.t = F, lgd = T, r.method = c('lm', 'loess'), span = 0.75){


  if(!is.list(data.in)){
    stop("List containing peaks and info required")
  }
  if(is.list(data.in)){
    peaks <- bct.tabwrap(data.in[[1]], c('numeric', 'data.frame'))
    info <- bct.tabwrap(data.in[[2]], c('factor', 'data.frame'))
  }

  if(missing(select)){
    cat("No column selection given, it will be set for the first five features.\n")
    select <- c(1:5)
  }

  b <- levels(info$Batch)
  qc <- which(info$SCode == 'ref')
  info.c <- bct.tabwrap(info, c('character', 'matrix'))

  # Rename Batches for plotting
  for(i in 1:length(b)){
    info.c[which(info.c[,I.b] == b[i]), I.b] <- i
  }

  # Rename QCs for plotting
  info.c[, I.g] <- 1
  info.c[qc, I.g] <- 2

  info.c <- bct.tabwrap(info.c, c('numeric', 'matrix'))


  peaks.s <- peaks[,select]
  if(length(select) > 1){
    peaks.s <- bct.tabwrap(peaks, c('numeric', 'matrix'))
  } else {
    peaks.s <- as.numeric(as.character(peaks.s))
  }

  # Input table for plotting
  table <- cbind(info.c, peaks.s)
  if(length(select) == 1){
    colnames(table)[4] <- colnames(peaks)[select]
  }
  table <- bct.tabwrap(table, c('numeric', 'data.frame'))
  table[,1:2] <- bct.tabwrap(table[,1:2], c('factor', 'data.frame'))
  colnames(table) <- gsub('X', '', colnames(table))

  table.m <- melt(table, id.vars = c('Batch', 'SCode','SeqNr'))

  if(!QC){
    if(seq){
      p <- ggplot(data = table.m, aes(x = SeqNr, y = value, shape = SCode)) +
           geom_point(aes(color = SCode)) + geom_line(aes(color = SCode)) +
           geom_smooth(method = r.method, se = F, span = span,
                  aes(x = SeqNr,
                      y = value, group = variable, color = variable), fullrange = T)
    } else {
      p <- ggplot(data = table.m, aes(x = Batch, y = value, shape = SCode)) +
           geom_point(aes(color = SCode)) + geom_line(aes(color = SCode)) +
           geom_smooth(method = r.method, se = F, span = span,
                       aes(x = Batch,
                           y = value, group = variable, color = variable), fullrange = T)
    }

    p <- p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                                axis.text = element_text(size = 13),
                                axis.title = element_text(size = 20),
                                plot.title = element_text(size = 10),
                                axis.line = element_line(size = 0.1),
                                axis.ticks = element_line(size = 0.8),
                                panel.border = element_rect(size = 1.2))
    if(seq){
      if(log.t){
        p <- p + labs('Injection Sequence', y = 'log(Intensity)', colour = table[,2])
      } else {
        p <- p + labs('Injection Sequence', y = 'Intensity', colour = table[,2])
      }
    } else {
      if(log.t){
        p <- p + labs('Batch', y = 'log(Intensity)', colour = table[,2])
      } else {
        p <- p + labs('Batch', y = 'Intensity', colour = table[,2])
      }
    }


    if(lgd){
      p <- p + guides(color = guide_legend(title = 'Variables:', override.aes = list(linetype = 0)),
                      shape = guide_legend(title = 'Sample group:'))
    } else {
      p <- p + theme(legend.position = 'none')
    }

    p <- p + scale_y_continuous(limits = c(min(peaks.s), max(peaks.s)))

    nms <- colnames(peaks)[select]

  } else {

    if(seq){
      p <- ggplot(data = table.m, aes(x = SeqNr, y = value, shape = SCode)) +
      geom_point(aes(color = SCode)) + geom_line(aes(color = SCode)) +
      stat_smooth(data = subset(table.m, SCode == 2), span = span,
                  aes(x = SeqNr,
                      y = value, group = variable, color = variable),
                  se = F, method = r.method, fullrange = T)

    } else {
    p <- ggplot(data = table.m, aes(x = Batch, y = value, shape = SCode)) +
      geom_point(aes(color = SCode)) + geom_line(aes(color = SCode)) +
      stat_smooth(data = subset(table.m, SCode == 2), span = span,
                  aes(x = Batch,
                      y = value, group = variable, color = variable),
                  se = F, method = r.method, fullrange = T)
    }

    p <- p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                                axis.text = element_text(size = 13),
                                axis.title = element_text(size = 20),
                                plot.title = element_text(size = 10),
                                axis.line = element_line(size = 0.1),
                                axis.ticks = element_line(size = 0.8),
                                panel.border = element_rect(size = 1.2))

    if(seq){
      if(log.t){
        p <- p + labs('Injection Sequence', y = 'log(Intensity)', colour = table[,2])
      } else {
        p <- p + labs('Injection Sequence', y = 'Intensity', colour = table[,2])
      }
    } else {
      if(log.t){
        p <- p + labs('Batch', y = 'log(Intensity)', colour = table[,2])
      } else {
        p <- p + labs('Batch', y = 'Intensity', colour = table[,2])
      }
    }

    if(lgd){
      p <- p + guides(color = guide_legend(title = 'Variables:', override.aes = list(linetype = 0)),
                      shape = guide_legend(title = 'Sample group:'))

    } else {
      p <- p + theme(legend.position = 'none')
    }

    p <- p + scale_y_continuous(limits = c(min(peaks.s), max(peaks.s)))
  }

  return(p)
}
